#!/usr/bin/env bash
# Creates a file (path) containing its PID
# Then kill and remove file
path="/var/run/holbertonscript.pid"
var="I hate the kill command"
echo $$ > "$path"
trap 'echo Y U no love me?!' SIGINT
trap 'pgrep -f 100-process_and_pid_file | xargs kill -9 & rm -f $path' SIGQUIT
trap 'echo $var & pgrep -f 100-process_and_pid_file | xargs kill -9 & rm -f $path' SIGTERM
h="0"
while [ $h ]
    do
	echo "To infinity and beyond"
	sleep 1
    done
