#!/usr/bin/env bash
# Displays numbers from 1 to 100 fizzbuzz
for ((h=1 ; h < 100 ; h++));
do
    if [ $((h % 3)) == 0 ] && [ $((h % 5)) == 0 ]; then
	echo "FizzBuzz"
    elif [ $((h % 3)) == 0 ]; then
	echo "Fizz"
    elif [ $((h % 5)) == 0 ]; then
	echo "Buzz"
    else
	echo "$h"
    fi
done						  
