#!/usr/bin/env bash
# This script is displays the time for 12 hours and 59 minutes
HOUR="0"
while [ $HOUR -lt 13 ]
do
    echo Hour: "$HOUR"
    MINUTES="1"
    while [ $MINUTES -lt 60 ]
    do
	  echo "$MINUTES"
	  MINUTES=$((MINUTES+1))
    done
    HOUR=$((HOUR+1))
done
