#!/usr/bin/env bash
# Execute web server with the user nginx
# and that it's listening on port 8080
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '2 i user nginx;' /etc/nginx/nginx.conf
pkill -f apache2
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
